export const petList = [
  {
    id: 1,
    nome: "Jujuba",
    descrição: "macho 30cm",
    "url da imagem": "http://www.jujuba.com.br",
    categoria: "cachorro",
    "data de nascimento": "03/10/2019",
    idade: "5 anos",
  },
  {
    id: 2,
    nome: "Bola de pelo",
    descrição: "famea 20cm",
    "url da imagem": "http://www.boladepelo.com.br",
    categoria: "gato",
    "data de nascimento": "12/02/2022",
    idade: "2 anos",
  },
  {
    id: 3,
    nome: "Maia",
    descrição: "femea 20cm",
    "url da imagem": "http://www.maia.com.br",
    categoria: "cachorro",
    "data de nascimento": "20/07/2021",
    idade: "3 anos",
  },
  {
    id: 1,
    nome: "Jujuba",
    descrição: "macho 30cm",
    "url da imagem": "http://www.jujuba.com.br",
    categoria: "cachorro",
    "data de nascimento": "03/10/2019",
    idade: "5 anos",
  },
  {
    id: 1,
    nome: "Jujuba",
    descrição: "macho 30cm",
    "url da imagem": "http://www.jujuba.com.br",
    categoria: "cachorro",
    "data de nascimento": "03/10/2019",
    idade: "5 anos",
  },
  {
    id: 1,
    nome: "Jujuba",
    descrição: "macho 30cm",
    "url da imagem": "http://www.jujuba.com.br",
    categoria: "cachorro",
    "data de nascimento": "03/10/2019",
    idade: "5 anos",
  },
  {
    id: 1,
    nome: "Jujuba",
    descrição: "macho 30cm",
    "url da imagem": "http://www.jujuba.com.br",
    categoria: "cachorro",
    "data de nascimento": "03/10/2019",
    idade: "5 anos",
  },
  {
    id: 1,
    nome: "Jujuba",
    descrição: "macho 30cm",
    "url da imagem": "http://www.jujuba.com.br",
    categoria: "cachorro",
    "data de nascimento": "03/10/2019",
    idade: "5 anos",
  },
];
